<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5IM24OK" failures="1" tests="3" name="Default test" time="12.719" errors="0" timestamp="2024-09-19T16:11:04 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.317">
    <failure type="java.lang.AssertionError" message="Failing this step intentionally to check the screenshot attached int the Report">
      <![CDATA[java.lang.AssertionError: Failing this step intentionally to check the screenshot attached int the Report
at org.testng.Assert.fail(Assert.java:99)
at awesomecucumber.stepdefinitions.ProductStepDefinitions.iShouldSeeAnError(ProductStepDefinitions.java:58)
at âœ½.I should see an error(file:///E:/GC%20Download/MasterSeleniumFramework_BDD/MasterSeleniumFramework_BDD/src/test/resources/features/add_to_cart.feature:61)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.328"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="8.222"/>
</testsuite> <!-- Default test -->
