<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5IM24OK" failures="1" tests="3" name="awesomecucumber.runners.MyTestNGRunnerTest" time="20.867" errors="0" timestamp="2024-09-19T16:11:04 IST" skipped="0">
  <testcase classname="awesomecucumber.runners.MyTestNGRunnerTest" name="runScenario" time="5.317">
    <failure message="Failing this step intentionally to check the screenshot attached int the Report" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this step intentionally to check the screenshot attached int the Report
at org.testng.Assert.fail(Assert.java:99)
at awesomecucumber.stepdefinitions.ProductStepDefinitions.iShouldSeeAnError(ProductStepDefinitions.java:58)
at âœ½.I should see an error(file:///E:/GC%20Download/MasterSeleniumFramework_BDD/MasterSeleniumFramework_BDD/src/test/resources/features/add_to_cart.feature:61)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="awesomecucumber.runners.MyTestNGRunnerTest" name="runScenario" time="7.328"/>
  <system-out/>
  <testcase classname="awesomecucumber.runners.MyTestNGRunnerTest" name="runScenario" time="8.222"/>
  <system-out/>
</testsuite> <!-- awesomecucumber.runners.MyTestNGRunnerTest -->
